import { invoke } from "@tauri-apps/api/core";

/**
 * Host-bound local-model tabs (`docs/sandbox_hardening_plan.md` Phase 2 / #150).
 *
 * A local-model driver tab (`vibe`, or `ollama launch <agent>`) must keep running
 * **on the host** even when its project's container toggle is on: it depends on
 * the host's Ollama server, `VIBE_HOME`, and each agent's host-side wiring, none
 * of which exists inside the image. That exemption is the one hole in an
 * otherwise total containment, so what grants it matters.
 *
 * It used to be granted by the tab carrying `TABTIVITY_LOCAL_MODEL` — which
 * `TabBar`/`NewTabMenu` set so the daily usage recap can break local-agent tabs
 * down by model. An authority decision keyed on a telemetry label: anything that
 * later set that var for a display reason would have handed out container
 * escapes, silently and with nothing failing.
 *
 * Now the tab mints a uid at creation, the backend records it as a file under
 * `<state_dir>/sessions/<project>/host_bound/`, and the spawn path checks for
 * that file. `TABTIVITY_LOCAL_MODEL` is a usage label again.
 *
 * The uid is minted here and persisted on the tab, because it has to survive a
 * relaunch and nothing else on the tab does — the tab's key and its PTY id are
 * both regenerated by `loadFromLayout`.
 */

/** A uid the backend will accept as a marker filename: `[A-Za-z0-9_-]`, ≤64. */
function mintUid(): string {
  const c = globalThis.crypto;
  if (c && typeof c.randomUUID === "function") return c.randomUUID();
  // A crypto-less environment (some test runners): still unguessable enough for
  // what this is — a name, not a secret — and the marker file is the authority.
  return `hb-${Math.random().toString(36).slice(2)}${Date.now().toString(36)}`;
}

/**
 * Mint and register a host-bound marker for a local-model tab about to be created
 * in `scope`. Returns the uid to store on the tab, or `undefined` when there is
 * nothing to register against (the root scope) or the backend refused.
 *
 * `undefined` is not a failure to handle loudly: a tab without a marker simply
 * runs inside the container like every other tab of a container-toggled project.
 * That is the safe direction — the model may be unreachable from inside, which is
 * a visible, diagnosable problem, unlike a silent escape.
 */
export async function registerHostBoundTab(scope: string): Promise<string | undefined> {
  if (!scope || scope === "root") return undefined;
  const uid = mintUid();
  try {
    await invoke("register_host_bound_tab", { projectId: scope, uid });
    return uid;
  } catch {
    return undefined;
  }
}
